// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discuss_probe.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDiscussProbeDecision = `-- name: CreateDiscussProbeDecision :one
INSERT INTO bot_discuss_probe_decisions (
  bot_id,
  session_id,
  requested_at_ms,
  activated,
  outcome,
  reason,
  model_id,
  input_tokens,
  output_tokens,
  cache_read_tokens,
  cache_write_tokens
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11
)
RETURNING id, team_id, bot_id, session_id, requested_at_ms, activated, outcome, reason, model_id, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, created_at
`

type CreateDiscussProbeDecisionParams struct {
	BotID            pgtype.UUID `json:"bot_id"`
	SessionID        pgtype.UUID `json:"session_id"`
	RequestedAtMs    int64       `json:"requested_at_ms"`
	Activated        bool        `json:"activated"`
	Outcome          string      `json:"outcome"`
	Reason           string      `json:"reason"`
	ModelID          pgtype.UUID `json:"model_id"`
	InputTokens      int32       `json:"input_tokens"`
	OutputTokens     int32       `json:"output_tokens"`
	CacheReadTokens  int32       `json:"cache_read_tokens"`
	CacheWriteTokens int32       `json:"cache_write_tokens"`
}

func (q *Queries) CreateDiscussProbeDecision(ctx context.Context, arg CreateDiscussProbeDecisionParams) (BotDiscussProbeDecision, error) {
	row := q.db.QueryRow(ctx, createDiscussProbeDecision,
		arg.BotID,
		arg.SessionID,
		arg.RequestedAtMs,
		arg.Activated,
		arg.Outcome,
		arg.Reason,
		arg.ModelID,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
	)
	var i BotDiscussProbeDecision
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.BotID,
		&i.SessionID,
		&i.RequestedAtMs,
		&i.Activated,
		&i.Outcome,
		&i.Reason,
		&i.ModelID,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.CreatedAt,
	)
	return i, err
}

const listDiscussProbeDecisions = `-- name: ListDiscussProbeDecisions :many
SELECT id, team_id, bot_id, session_id, requested_at_ms, activated, outcome, reason, model_id, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, created_at
FROM bot_discuss_probe_decisions
WHERE team_id = public.memoh_current_team_id()
  AND session_id = $1
ORDER BY requested_at_ms DESC, created_at DESC
LIMIT $2
`

type ListDiscussProbeDecisionsParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	RowLimit  int32       `json:"row_limit"`
}

func (q *Queries) ListDiscussProbeDecisions(ctx context.Context, arg ListDiscussProbeDecisionsParams) ([]BotDiscussProbeDecision, error) {
	rows, err := q.db.Query(ctx, listDiscussProbeDecisions, arg.SessionID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotDiscussProbeDecision
	for rows.Next() {
		var i BotDiscussProbeDecision
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.BotID,
			&i.SessionID,
			&i.RequestedAtMs,
			&i.Activated,
			&i.Outcome,
			&i.Reason,
			&i.ModelID,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
